### ISSUE TITLE
Crash w/ Forge v28.1.40

### ISSUE THREAD

**Issue by WenXin20** [sp614x/optifine#2953]
`Minecraft v1.14.4`
`Forge v28.1.40`
`Optifine vHD_U_F4_Pre7`

With only Optifine in the mods folder, I get the following crash on game load.
[Crash Report](https://gist.github.com/WenXin20/af610f4cd3e5d8ab7d4c7f8b9b8bd930)

**Comment by sp614x** [comment]
It is compatible with Forge 28.1.26, not 1.40.

**Comment by WenXin20** [comment]
It works fine with v28.1.39, so I assumed something with Forge changed in the newest update to break compatiblity.

**Comment by ppoozl** [comment]
Build: 1.14.4-28.1.40 - Mon Oct 07 22:18:52 GMT 2019
	David Quintana:
		Fix forge blockstates and custom model loading (#6154)
		* Reimplement forge blockstates variant through the use of a
		pseudo-model that handles the model loading, retexturing, custom data,
		etc. on behalf of the blockstates loader. This model gets injected into
		the model registry with an autogenerated unique name, to not collide
		with other model locations.
		* Fix model loaders not being properly initialized by calling the reload
		method from the loader register function. In 1.12, registering a reload
		listener caused the listener to be called right away from the register
		method. This is not true anymore.
--------------------------------------------------------------------------------------------------------
So forge may do something on render

**Comment by pumbelixpl** [comment]
Use OptiFine 1.14.4 HD U F3. Work.

**Comment by NorgerLegacy** [comment]
I have same issue, also tried latest 28.1.41 for forge and pre 7 and pre 8.( i tried the main jar and extracting the mod file) but still cant get optifine to work with latest forge.

(from pre 8mod.jar) The game crashed whilst rendering overlay
Error: java.lang.NoSuchMethodError: net.minecraft.client.renderer.model.ModelBakery.<init>(Lnet/minecraft/resources/IResourceManager;Lnet/minecraft/client/renderer/texture/AtlasTexture;Lnet/minecraft/client/renderer/color/BlockColors;Z)V

[crash-2019-10-10_15.58.04-client.txt](https://github.com/sp614x/optifine/files/3714389/crash-2019-10-10_15.58.04-client.txt)

hope this may help

**Comment by pumbelixpl** [comment]
The latest version of Forge 28.1.42 does not work with Optifine

**Comment by sp614x** [comment]
Fixed, coming in next preview.

**Comment by pumbelixpl** [comment]
> Fixed, coming in next preview.

Thank you. now works on the new Forge
