### ISSUE TITLE
Optifine 1.13 alpha crashing at start

### ISSUE THREAD

**Issue by igooreqq** [sp614x/optifine#1692]
Hi, when i'm using Minecraft 1.13 Optifine Alpha, my launcher is crashing.

[19:54:51] [main/INFO]: Loading tweak class name net.minecraft.launchwrapper.VanillaTweaker
[19:54:51] [main/INFO]: Using primary tweak class name net.minecraft.launchwrapper.VanillaTweaker
[19:54:51] [main/INFO]: Calling tweak class net.minecraft.launchwrapper.VanillaTweaker
Exception in thread "main" java.lang.NoClassDefFoundError: org/objectweb/asm/ClassVisitor
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
	at java.lang.Class.getConstructor0(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88)
	at net.minecraft.launchwrapper.VanillaTweaker.injectIntoClassLoader(VanillaTweaker.java:16)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: org.objectweb.asm.ClassVisitor
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 8 more
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release

I'm using SK Launcher 2.8 but it doesn't work on SK Launcher 3.0 version too.
Please, somebody can help me ?

**Comment by skmedix** [comment]
SKlauncher will get a special update in a few days. Atm you can use a solution from #1635 with SKL 3.0
