### ISSUE TITLE
[Bug] OptiFine 1.19.2 Strips BakedQuad constructor, causing crashes

### ISSUE THREAD

**Issue by raoulvdberge** [sp614x/optifine#7127]
## Description of Issue
See: https://github.com/refinedmods/refinedstorage/issues/3386

Optifine is stripping away a constructor introduced by Forge in `BakedQuad`, causing this crash:
```
Caused by: java.lang.NoSuchMethodError: 'void net.minecraft.client.renderer.block.model.BakedQuad.<init>(int[], int, net.minecraft.core.Direction, net.minecraft.client.renderer.texture.TextureAtlasSprite, boolean, boolean)'
	at net.minecraftforge.client.model.pipeline.QuadBakingVertexConsumer.m_5752_(QuadBakingVertexConsumer.java:131) ~[forge-1.19.2-43.1.32-universal.jar%23302!/:?] {re:classloading}
```

The constructor is introduced in https://github.com/MinecraftForge/MinecraftForge/pull/9019

## Steps to Reproduce
Run any Forge mod that calls the ``net.minecraft.client.renderer.block.model.BakedQuad`` function, a crash will occur when the item is attempted to be rendered.
- Refined Storage: https://github.com/refinedmods/refinedstorage/issues/3386
- Applied Energistics: https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/6620
- Mekanism: https://github.com/mekanism/Mekanism/issues/7626
- Immersive Engineering: https://github.com/BluSunrize/ImmersiveEngineering/issues/5446
- ...

## OptiFine Version
preview_OptiFine_1.19.2_HD_U_I1_pre2.

## Installation Method
Dropped the jar in mods folder.

## Fabric/Forge Version
1.19.2-forge-43.1.32

## Other Installed Mods
See above (RS, AE, Mekanism)

## Log Files/Crash Reports
See the linked bug reports.

**Comment by Ari-RERA-43** [comment]
Does it happen on Forge 43.1.1, which is the intended Forge version for that OptiFine version?

**Comment by ZenIsBestWolf** [comment]
Temporarily can be remedied by using Forge 43.1.1, the actual intended Forge version, or 43.1.23.

This crash begins on Forge 43.1.24 (when the commit referenced in the issue was introduced.

Can confirm any mod using BakedQuad appears to crash on 43.1.24 and above with OptiFine.

**Comment by slivesay30** [comment]
I am also having this crash.  I use the following mods:
![image](https://user-images.githubusercontent.com/68707956/198894713-0c746ec2-7b17-412c-8236-26c62e9ce33c.png)

The latest Mekanism / AE2 mods require forge 43.1.44 or newer.  Just wanted to provide additional details.  Thanks

**Comment by hitubhg** [comment]
im also getting this crash

**Comment by sp614x** [comment]
Fixed in latest preview.

**Comment by ZenIsBestWolf** [comment]
Fixed in I1 pre3
