### ISSUE TITLE
[Crash] OptiFine 1.18.2_HD_U_H7 crash with Forge-1.18.2-40.1.60 when entering into world

### ISSUE THREAD

**Issue by TimLee9024** [sp614x/optifine#6974]
## Description of Issue
Due to [the recent change made by Forge](https://github.com/MinecraftForge/MinecraftForge/commit/1b25285462f99790e0426cc4ecdcf0af06a64575) (Forge-1.18.2-40.1.58), once enter into a world the game crashed.

## Steps to Reproduce
1. Open the game.
2. Enter into a world save.

## OptiFine Version
OptiFine 1.18.2_HD_U_H7

## Installation Method
Double click OptiFine_1.18.2_HD_U_H7.jar, and extract OptiFine_1.18.2_HD_U_H7_MOD.jar into mods folder.

## Fabric/Forge Version
Forge-1.18.2-40.1.60

## Other Installed Mods
None

## Log Files/Crash Reports
[crash-2022-07-10_09.57.22-server.txt](https://github.com/sp614x/optifine/files/9078276/crash-2022-07-10_09.57.22-server.txt)
[debug.log](https://github.com/sp614x/optifine/files/9078278/debug.log)

## Prior Testing
Everything works fine when downgrade to Forge-1.18.2-40.1.57 or remove OptiFine.

## Additional Information
It seem like that the method add by Forge patch was removed by OptiFine patch and cause NoSuchMethodError once that method being called.

**Comment by TimLee9024** [comment]
I

> Isn't that because OptiFine HD U H7 1.18.2 is only for Forge 40.0.24 and below?

In the past, OptiFine usually compatible with higher version of Forge than it claim for.
So I usually think the Forge version appear in OptiFine website is minimum version requirement for that version of OptiFine.
For example, OptiFine 1.16.5 HD U G8(Forge 36.1.0) can work with latest version of 1.16.5 Forge (36.2.35).
Since it is almost no problem there, sp614x don't even bother to update OptiFine and there is no need change compatible version constantly when Forge get update.

If it is inappropriate to open this kind of issue here, there should be a comment  in "Bug report" issue draft prohibited for it.

**Comment by fayer3** [comment]
I think it is appropriate to open these issues, so they can be fixed in the future

**Comment by Nik-mmzd** [comment]
> Isn't that because OptiFine HD U H7 1.18.2 is only for Forge 40.0.24 and below?

Usually "Requires Forge x.x.x" means *minimal* compatible Forge version is x.x.x

**Comment by Firat20026** [comment]
Try using Forge 41.1.0, for now at least. I wanted to install the newest Create update with Optifine, it seems there was a change in the codes at some point afterward 41.1. But looks like it works with that and since it's a minor version all other mods should be capable.

**Comment by FrustratedDucky** [comment]
Hey dude I'm trying to add optifine to my current modded minecraft on forge 40.1.57 could you explain how you got it to all work for you cause I keep getting exit code 1 :C

**Comment by Firat20026** [comment]
@FrustratedDucky like I said, try using forge 41.1.**0**

**Comment by ThunderTheFurry** [comment]
@FrustratedDucky just install Forge version 41.1.0 for you Modpack and use the mirror version of Optifine.

[Optifine.zip](https://github.com/sp614x/optifine/files/9130871/Optifine.zip)

**Comment by flin7101** [comment]
Having similar issue and just wanted to confirm that using forge 41.1.0 ( which is a 1.19 release) was not a typo and would work with 1.18.2 ?

**Comment by moninformateur** [comment]
People didn't actually read the issue it seems because yes, do not install 41.1.0, it is a 1.19 release.

**Comment by Tetalica** [comment]
Forge version 40.1.53 doesn't have this bug, however some mods already require more recent forge version so it's still not ideal but at least it's playable.

**Comment by moninformateur** [comment]
> Forge version 40.1.53 doesn't have this bug, however some mods already require more recent forge version so it's still not ideal but at least it's playable.

It is confirmed that the breaking change in forge occured in 40.1.58. Optifine for 1.18.2 will work up to Forge 40.1.57 until (if ever) the team decides to fix it. We can only hope.

**Comment by IDKZAL** [comment]
Let's hope they push a fix for this :/

**Comment by Boegame** [comment]
> It is confirmed that the breaking change in forge occured in 40.1.58. Optifine for 1.18.2 will work up to Forge 40.1.57 until (if ever) the team decides to fix it. We can only hope.

I've tried that, but I'm still getting booted without Minecraft ever launching and I'm not getting any useful logs from it, does anyone have any other ideas on how to get it working? The only way I found so far is to lower Forge all the way to 40.0.24 but that removes 90% of the mods I wanted.

**Comment by moninformateur** [comment]
> > It is confirmed that the breaking change in forge occured in 40.1.58. Optifine for 1.18.2 will work up to Forge 40.1.57 until (if ever) the team decides to fix it. We can only hope.
> 
> I've tried that, but I'm still getting booted without Minecraft ever launching and I'm not getting any useful logs from it, does anyone have any other ideas on how to get it working? The only way I found so far is to lower Forge all the way to 40.0.24 but that removes 90% of the mods I wanted.

If it doesn't work with 40.1.57, then the crash has nothing to do with Optifine. Check your other mods.

**Comment by Boegame** [comment]
I guess I didn't think there could be a conflict between Optifine and some random mod, I'll have to install them one by one and launch to see whats causing it.

**Comment by DaniMadrid2** [comment]
It does not crash for me entering a server's world with the initial optifine version (1.18.2_HD_U_H7)

**Comment by sp614x** [comment]
Fixed in latest preview.
Duplicate of #7009.

**Comment by LGN-Ytt** [comment]
You can look at the pre1 that supports higher versions. But is adfoucus not working for yall? It isn't happy for me

**Comment by FinEie** [comment]
Guys im so sorry for the late response but for anyone having the same issue, if you want to keep the game version on 1.18.2 for lets say a specific group of mods or something like that, then simply bumping up your optifine version from "OptiFine HD U H7" to "OptiFine HD U H9 pre3" solves your issue. (you have to click the preview versions option above OptiFine HD U H7)

**Comment by cxrsair** [comment]
> Guys im so sorry for the late response but for anyone having the same issue, if you want to keep the game version on 1.18.2 for lets say a specific group of mods or something like that, then simply bumping up your optifine version from "OptiFine HD U H7" to "OptiFine HD U H9 pre3" solves your issue. (you have to click the preview versions option above OptiFine HD U H7)

Ive tried that. which forge version exactly are you using? I've tried forge 1.18.2 40.0.24, 40.2.1 and the most recent 40.2.9 with the optifine your talking about. I've tried everything i can think of and none of it works. If it continues so, i'll just not be able to use shaders with my forge mods :|
