### ISSUE TITLE
Instant crash on fresh installation (1.14.2 pre13)

### ISSUE THREAD

**Issue by piiiickle** [sp614x/optifine#2499]
Toshiba Satellite L55-C5272 running Windows 10. Optifine works in every version except 1.14/1.14.2 for me. Vanilla 1.14.2 works fine. Tried a fresh installation, didn't help. I used tlauncher, normal launcher didn't have an option for Optifine.
[log.txt](https://github.com/sp614x/optifine/files/3293475/log.txt)

**Comment by derixithy** [comment]
I have the some with pre9, pre10, pre12 and pre13, installed the original launcher to use optifine and deleted .minecraft to test pre13, but did not help.
[launcher_log.txt](https://github.com/sp614x/optifine/files/3294411/launcher_log.txt)

**Comment by Boptilop** [comment]
I can confirm this happens to me too. 

macOS 10.14.5.

**Comment by sp614x** [comment]
Failed to dynamically load library: /var/folders/6r/dj90nqt97gbfx23t8f6pxxc00000gn/T/04b9-72c9-44e7-10a9/libopenal.dylib

**Comment by sp614x** [comment]
@piiiickle "NoClassDefFoundError: ru/turikhay/util/windows/wmi/WMI"
Problem with TLauncher, not related to OptiFine.

**Comment by sp614x** [comment]
@derixithy "java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader"
OptiFine is only compatible with Java 8. 
The error comes when it is running with Java 9 or newer.

**Comment by Boptilop** [comment]
@sp614x This issue doesn't happen in vanilla. I'd appreciate if it were investigated further.
